language: python
sudo: false
python:
    - "3.4"
    - "3.5"
    - "3.6"

services:
  - redis-server

cache:
    - pip

install:
    - pip install codecov
    - pip install coveralls
    - pip install -r requirements.txt

script:
  - coverage run -p -m pytest tests

branches:
  only:
    - dev

after_success:
    - coverage combine
    - coveralls
    - codecov