language: python
sudo: false
python:
    - "3.5"

services:
  - mysql
  - redis-server

cache:
    - pip

before_install:
    - mysql -e 'create database weibo DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

install:
    - pip install -r test-requirements.txt
    - pip install -r requirements.txt

script:
  - coverage run -p -m pytest tests

branches:
  only:
    - master

after_success:
    - coverage combine
    - codecov
    - coveralls